set nocompatible
filetype off

" Vundle setup
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'sjl/badwolf'
Plugin 'tpope/vim-fugitive'

call vundle#end()
filetype plugin indent on

syntax on
set number
set background=dark
colorscheme badwolf
